# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=30)),
                ('batch_no', models.IntegerField(max_length=5)),
                ('faculty', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
