# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='batch_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
