# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_auto_20190618_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Nepali', models.IntegerField()),
                ('Computer', models.IntegerField()),
            ],
        ),
    ]
