# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-23 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0003_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Computer',
            new_name='computer',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='English',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Maths',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Nepali',
            new_name='nepali',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Roll',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Science',
            new_name='science',
        ),
    ]
