# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0004_auto_20190623_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
