# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
