# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0007_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentinfo.Info'),
        ),
    ]
