# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0008_marks_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='terminal',
            field=models.CharField(blank=True, choices=[('first_term', 'first_term'), ('second_term', 'second_term'), ('third_term', 'third_term')], max_length=50, null=True),
        ),
    ]
