# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0009_marks_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='name',
        ),
    ]
