# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0010_remove_marks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='D:\\djangoproject\\Project\\student\\studentinfo\\static\\images\\dummyprofile.png', null=True, upload_to='documents/'),
        ),
    ]
