# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0011_auto_20190625_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='\\static\\images\\dummyprofile.png', null=True, upload_to='documents/'),
        ),
    ]
