# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0012_auto_20190625_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='documents\\dummyprofile.png', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='terminal',
            field=models.CharField(blank=True, choices=[('first_term', 'first_term'), ('second_term', 'second_term'), ('third_term', 'third_term')], default='first_term', max_length=50, null=True),
        ),
    ]
