# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0015_auto_20190626_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
