# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0018_marks_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='documents/dummyprofile.png', null=True, upload_to='documents/'),
        ),
    ]
