# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-03 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0020_marks_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='gpa',
            new_name='percent',
        ),
    ]
