# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0021_auto_20190703_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
