# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0022_marks_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='grade',
        ),
    ]
