# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0026_marks_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='account',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='eph',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='social',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
    ]
