# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0028_remove_marks_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
