# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0030_remove_marks_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='avg',
        ),
    ]
