# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0031_remove_marks_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='terminal',
            field=models.CharField(blank=True, choices=[('first_term', 'first_term'), ('second_term', 'second_term'), ('third_term', 'third_term'), ('final_result', 'final_result')], default='first_term', max_length=50, null=True),
        ),
    ]
