# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0033_auto_20190710_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('final_science', models.IntegerField()),
                ('final_maths', models.IntegerField()),
                ('final_nepali', models.IntegerField()),
                ('final_computer', models.IntegerField()),
                ('final_social', models.IntegerField()),
                ('final_english', models.IntegerField()),
                ('final_account', models.IntegerField()),
                ('final_total', models.IntegerField(blank=True, null=True)),
                ('final_percent', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
