# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0034_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='roll',
        ),
        migrations.AddField(
            model_name='final',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentinfo.Info'),
        ),
        migrations.AddField(
            model_name='info',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
