# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0035_auto_20190711_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='final_eph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_computer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_maths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_nepali',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_science',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='final_social',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
