# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0036_auto_20190712_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='final_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
