# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0038_auto_20190712_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attendance', models.IntegerField(blank=True, null=True)),
                ('extra_cirruculum_remarks', models.TextField(blank=True, null=True)),
                ('academic_activity_remarks', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academicextra',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentinfo.Info'),
        ),
    ]
