# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0039_auto_20190712_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
